const categoryActionTypes = {
    FETCH_ALL_CATEGORY_SUCCESS: 'FETCH_ALL_CATEGORY_SUCCESS',
    FETCH_ALL_CATEGORY_STARTED: 'FETCH_ALL_CATEGORY_STARTED',
    FETCH_ALL_CATEGORY_FAIL: 'FETCH_ALL_CATEGORY_FAIL',

    FETCH_CATEGORY_BY_NAME_SUCCESS: 'FETCH_CATEGORY_BY_NAME_SUCCESS',
    FETCH_CATEGORY_BY_NAME_STARTED: 'FETCH_CATEGORY_BY_NAME_STARTED',
    FETCH_CATEGORY_BY_NAME_FAIL: 'FETCH_CATEGORY_BY_NAME_FAIL',

    CLEAR_CATEGORIES: 'CLEAR_CATEGORIES'
}

export { categoryActionTypes };