const searchActionTypes = {
    FETCH_SEARCH_STARTED: 'FETCH_SEARCH_STARTED',
    FETCH_SEARCH_SUCCESS: 'FETCH_SEARCH_SUCCESS',
    FETCH_SEARCH_FULL_SUCCESS: 'FETCH_SEARCH_FULL_SUCCESS',
    FETCH_SEARCH_FAILED:  'FETCH_SEARCH_FAILED'
};

export { searchActionTypes };