export const storeActionTypes = {
    FETCH_STORE_STARTED: 'FETCH_STORE_STARTED',
    FETCH_STORE_SUCCESS: 'FETCH_STORE_SUCCESS',
    FETCH_STORE_FAILED: 'FETCH_STORE_FAILED',

    FETCH_STORES_STARTED: 'FETCH_STORES_STARTED',
    FETCH_STORES_SUCCESS: 'FETCH_STORES_SUCCESS',
    FETCH_STORES_FAILED: 'FETCH_STORES_FAILED'
}