const productActionTypes = {
    FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
    FETCH_PRODUCT_STARTED: 'FETCH_PRODUCT_STARTED',
    FETCH_PRODUCT_FAIL: 'FETCH_PRODUCT_FAIL',

    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_STARTED: 'FETCH_PRODUCTS_STARTED',

    FETCH_PRODUCTS_PAGINATED_SUCCESS: 'FETCH_PRODUCTS_PAGINATED_SUCCESS',
    FETCH_PRODUCTS_PAGINATED_STARTED: 'FETCH_PRODUCTS_PAGINATED_STARTED',

    FETCH_PRODUCTS_FAIL: 'FETCH_PRODUCTS_FAIL',

    FETCH_PRODUCT_BY_BRAND_NAME_SUCCESS: 'FETCH_PRODUCT_BY_BRAND_NAME_SUCCESS',
    FETCH_PRODUCT_BY_BRAND_NAME_STARTED: 'FETCH_PRODUCT_BY_BRAND_NAME_STARTED',
    FETCH_PRODUCT_BY_BRAND_NAME_FAIL: 'FETCH_PRODUCT_BY_BRAND_NAME_FAIL',

    FETCH_PRODUCT_RELATED_BY_NAME_SUCCESS: 'FETCH_PRODUCT_RELATED_BY_NAME_SUCCESS',
    FETCH_PRODUCT_RELATED_BY_NAME_STARTED: 'FETCH_PRODUCT_RELATED_BY_NAME_STARTED',
    FETCH_PRODUCT_RELATED_BY_NAME_FAIL: 'FETCH_PRODUCT_RELATED_BY_NAME_FAIL',

    CLEAR_PRODUCTS: 'CLEAR_PRODUCTS',
    CLEAR_PRODUCT: 'CLEAR_PRODUCT'
}

export { productActionTypes };